### ISSUE TITLE
it seems the model file FAN does not exist, could you please share us with it, thank you very much

### ISSUE THREAD

**Issue by chengyuz** [1adrianb/2D-and-3D-face-alignment#1]

**Comment by 1adrianb** [comment]
@chengyuz Thanks a  lot for reporting this! The download links should work now.
You can run the code as:
```bash
th main.lua -path /path_to_the_dataset/ -model /path_to_the_model/model.t7
```
where the path to the dataset must be a folder containing png or jpeg images alongside their corresponding *.t7 ot *.pts points. An example of such dataset is the LS3D-W balanced available on our page.

**Comment by chengyuz** [comment]
thank you for your reply~
