### ISSUE TITLE
somequestion about dockerfile

### ISSUE THREAD

**Issue by PyJulie** [1adrianb/2D-and-3D-face-alignment#11]
now i have gpu driver and nvidia-docker on my machine,can i use the dockerfile directly? Do I need to install CUDA on my machine?

**Comment by 1adrianb** [comment]
Hi @PyJulie, as per [nvidia prerequisties](https://github.com/NVIDIA/nvidia-docker/wiki/Installation#prerequisites) NVIDIA driver + nvidia-modprobe should be enough. 

If you want to use the docker file directly you need to build the Docker image on your host something like this:  ``docker build -t facealignment .`` where facealignment is going to the tag name. Once this is done you can either use the jupyter server and access the code via a browser or daemonise(detach) it.
For instructions on how to do this and do X forwarding please see [here](https://github.com/Kaixhin/dockerfiles#cuda) or [here](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/).

If you have other problems with running it feel free to open an issue.
