### ISSUE TITLE
Some errors when i run demo

### ISSUE THREAD

**Issue by PyJulie** [1adrianb/2D-and-3D-face-alignment#12]
I put the 2d-fan and dataset in the demo,when i run th main.lua,it occurs:
![screenshot from 2017-09-11 09-01-13](https://user-images.githubusercontent.com/19531609/30254847-89e401d6-96d0-11e7-970e-00c29dfed9e0.png)
I tried to install npy4th, but failed, have you ever meet this error? thx

**Comment by 1adrianb** [comment]
@PyJulie, if you look at the very bottom of the error it says that it's actually an warning. The package is optional so the code should run fine.
Please also run ``the main.lua -help`` to see the appropriate flags.

**Comment by PyJulie** [comment]
@1adrianb I tried every flags,but sadly, whatever I use, it shows the same error,just same as what in the picture.

**Comment by 1adrianb** [comment]
@PyJulie can you try to clone again the repo and retry ?

**Comment by 1adrianb** [comment]
@PyJulie While the issue is fixed if you still have any issues please also check the python version which should be easier to setup.
