### ISSUE TITLE
Does network predict zero-based coordinates?

### ISSUE THREAD

**Issue by ablavatski** [1adrianb/2D-and-3D-face-alignment#13]
Could you confirm that your models predict zero-based coordinates and you need to shift them to one-based for correct metrics calculation?

https://github.com/1adrianb/2D-and-3D-face-alignment/blob/ab9eceb1aab8093b4b85819f7d2bd8e0b431fab3/main.lua#L112

Thanks in advance.

**Comment by 1adrianb** [comment]
@ablavatski  Yes you are correct, I will include this in the transform function because now it looks a bit hacky.

**Comment by ablavatski** [comment]
@1adrianb Thanks for the fast response!
