### ISSUE TITLE
Run model on CPU

### ISSUE THREAD

**Issue by andrewsanders0** [1adrianb/2D-and-3D-face-alignment#15]
How can I run it if I don't have a gpu?

**Comment by 1adrianb** [comment]
Hi, @andrewsanders0 
In order to run the model on a CPU make sure to (1) convert all [cudnn layer](https://github.com/soumith/cudnn.torch) to nn doing something like this: ``cudnn.convert(model, nn)`` and (2) the move the model to the cpu with ``model:float()``.
