### ISSUE TITLE
How fast is the program running? 

### ISSUE THREAD

**Issue by Hardold** [1adrianb/2D-and-3D-face-alignment#16]

**Comment by 1adrianb** [comment]
Hi @Hardold, on a GPU expect between 15-25fps (of course it will highly depend on the GPU you are using). The 3D one should be slighly slower.
I realised that some people may require a faster version so I will try to release very soon some smaller models described in the paper which should run up to 4x faster (with only a very small drop in performance). Let me know if you have any other questions.
