### ISSUE TITLE
does it work with Torch7 with LuaJIT 2.1.0-beta1?

### ISSUE THREAD

**Issue by ynotstartups** [1adrianb/2D-and-3D-face-alignment#18]
/home/mmf159/torch-cl/install/bin/luajit: /home/mmf159/torch-cl/install/share/lua/5.1/trepl/init.lua:384: 
    /home/mmf159/torch-cl/install/share/lua/5.1/trepl/init.lua:384: attempt to index a string value
    stack traceback:
    	[C]: in function 'error'
    	/home/mmf159/torch-cl/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    	main.lua:12: in main chunk
    	[C]: in function 'dofile'
    	...9/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    	[C]: at 0x00405e90

is it a problem of version of LuaJIT 2.1.0-beta1?

I am trying to run https://github.com/AaronJackson/vrn

**Comment by 1adrianb** [comment]
Hi @ynotstartups could you give more details and a full stack if possible since the error seems unrelared to my code. Line 12 just requires a package ('cunn').

**Comment by 1adrianb** [comment]
Also I see that you are using torch-cl, is that the open cl based torch?
