### ISSUE TITLE
fb-python cannot installed successfully?

### ISSUE THREAD

**Issue by happsky** [1adrianb/2D-and-3D-face-alignment#19]
Thanks for you sharing this code, but I cannot install fb-python correctly, when I run `luarocks make rockspec/fbpython-0.1-1.rockspec`, the following error occurs:

cmake -E make_directory build &&
        cd build &&
        cmake -DROCKS_PREFIX=/home/hao/torch/install/lib/luarocks/rocks/fbpython/0.1-1 \
              -DROCKS_LUADIR=/home/hao/torch/install/lib/luarocks/rocks/fbpython/0.1-1/lua \
              -DROCKS_LIBDIR=/home/hao/torch/install/lib/luarocks/rocks/fbpython/0.1-1/lib \
              .. &&
        make
    
-- Found Torch7 in /home/hao/torch/install
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required
  is at least "2.7.13" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindPythonLibs.cmake:208 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:47 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/hao/fblualib/fblualib/python/build/CMakeFiles/CMakeOutput.log".

Thanks you in advance!

**Comment by 1adrianb** [comment]
Hi @happsky ,
It looks like the python-devel package you are using has a different version to the python one (2.7.6 vs 2.7.13). Please make sure both of them are at the same version or add the correct path to ``LD_LIBRARY_PATH``.

If you still have issue please check wither the Docker image provided wich should offer you an working environment or use the python version available [here](https://github.com/1adrianb/face-alignment)
