### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xleeeon** [1adrianb/2D-and-3D-face-alignment#23]
Hi, I installed all the requirements described in the readme. Howeve, I still get something showed below.

![screenshot from 2017-11-21 18-23-44](https://user-images.githubusercontent.com/28063874/33106844-296d2bb0-cee9-11e7-8026-9fda6ff464ed.png)

Please help

**Comment by Kshitij08** [comment]
@xleeeon Did you find any solution for this??
