### ISSUE TITLE
Install fb-python on windows? 

### ISSUE THREAD

**Issue by zhaoyuanxing** [1adrianb/2D-and-3D-face-alignment#24]
I install fb-python on windows but get such message：

`
E:\Work\Lib\2D-and-3D-face-alignment>luarocks search python

python - Search results for Lua 5.1:
====================================

Rockspecs and source rocks:
---------------------------

fbpython
   0.1-2 (rockspec) - https://raw.githubusercontent.com/torch/rocks/master

python
   scm-0 (rockspec) - https://raw.githubusercontent.com/torch/rocks/master

E:\Work\Lib\2D-and-3D-face-alignment>luarocks install fbpython
Installing https://raw.githubusercontent.com/torch/rocks/master/fbpython-0.1-2.rockspec

Error: This rockspec for fbpython does not support win32, windows platforms.
`

How to install fb-python on windows? 

thank you

**Comment by 1adrianb** [comment]
Unfortunately, fb.python doesn't work on windows. The python parts are used to interface the code with dlib (for face detection) and for plotting the points (matplotlib). You can safely remove this parts but you will need another way to handle the plotting and the face detection. For plotting you can probably use visdom package from facebook.

**Comment by zhaoyuanxing** [comment]
thank you
