### ISSUE TITLE
LS3D-W Checksum

### ISSUE THREAD

**Issue by elbaro** [1adrianb/2D-and-3D-face-alignment#25]
The dataset is large. Can you provide md5sum of LS3D-W.tar.gz?

Also some questions:
- Are 2d-FAN and 3d-FAN trained on LS3D-W? Section 3.1 says 300-W-LP is used for training.
- Does Figure9 show the result for one global model trained on LS3D-W and tested on each (a)-(f) testset?
- Do you have a plan for binarized depth network?

**Comment by 1adrianb** [comment]
Hi @elbaro,

Sure, here is the md5sum: ``3705cf6973e7fd17f9ddf1cb509ca828 `

Regarding your questions:

- 2D-FAN and 3D-FAN were trained on 300-W-LP. The models available are following the training sets descrbed in the paper.
- Yes, that's correct.
- Not at the moment, but it is mostly a matter of retraining the network in a binarized setting.
