### ISSUE TITLE
About .mat file

### ISSUE THREAD

**Issue by liuhengli** [1adrianb/2D-and-3D-face-alignment#26]
The Mat file in the '300W_LP' dataset folder and in the 'landmarks' is different. I want to know about how to use the Mat file in the '300W_LP' dataset folder or its role.Thanks

**Comment by 1adrianb** [comment]
Hi @liuhengli,

Some of the files contain the pre-warped points while other contain the original 2D ones. The training code is already preconfigured to read the correct ones. Depending on your needs I suggest you looking into the description provided by the authors of 300W-LP [here](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm).
