### ISSUE TITLE
Can not run this demo on CPU

### ISSUE THREAD

**Issue by xdr94** [1adrianb/2D-and-3D-face-alignment#31]
When I run this demo with 2D-FAN model and set "-device cpu", it ended with error "In 1 module of nn.Sequential: /home/v-doxu/torch/install/share/lua/5.1/cudnn/init.lua:171: assertion failed!"

**Comment by 1adrianb** [comment]
Hi @xdr94,

Unfortunatelly the current models are cuda only, converting them is possible but not really straight-forward due to nngraph limitations. You can however try the pytorch models. Please note that the performance is not identical however.
