### ISSUE TITLE
Regarding licence of model file and dataset.

### ISSUE THREAD

**Issue by selva18** [1adrianb/2D-and-3D-face-alignment#32]
hi Adrian,
I have gone through the repository and found that the license type used in this repository is BSD 3-Clause "New" or "Revised".
1.Is the model file also covered under BSD 3-Clause "New" or "Revised" license?
2.With your knowledge, any idea about the licensing of datasets you used?

**Comment by 1adrianb** [comment]
@selva18 

By no means I can offer a legal advice.
The code, the models and the prediction are lincesed under BSD 3-Clause.  However, we do not own the images and such you may need to check this.

**Comment by selva18** [comment]
@1adrianb thanks for the reply.
You mentioned above " you may need to check this.". Any link you like to share.

**Comment by 1adrianb** [comment]
The images are taken from AFLW, 300W and 300VW Datasets. I am unsure what is the license of the images collected by them.

**Comment by selva18** [comment]
@1adrianb ok thanks
