### ISSUE TITLE
Scale factor in utils transform and get_normalisation

### ISSUE THREAD

**Issue by abskjha** [1adrianb/2D-and-3D-face-alignment#36]
First of all thanks for such a wonderful library.
Factor deciding scale in utils.get_normalisation is 195 :  `scale = (math.abs(maxX-minX)+math.abs(maxY-minY))/195`
While the same for utils.transform is 200: `h = 200*scale`
Shouldn't both be same? Either 200 or 195.

**Comment by 1adrianb** [comment]
Hi @abskjha, yes they should be, in practice you won't see much difference however between the two. Will fix this, thanks!
