### ISSUE TITLE
Groundtruth bounding box for training

### ISSUE THREAD

**Issue by yuanliu939** [1adrianb/2D-and-3D-face-alignment#38]
We did not find the groundtruth bounding boxes in the LS3D-W dataset. Is there anyway to obtain them?

**Comment by 1adrianb** [comment]
Hi @linthieda,

Sorry for delay. During testing we used a perturbed ground truth bounding box. However, for computing the metrics we use defined the bounding box as the tight one: the one tha fully encloses all the facial landmarks.
