### ISSUE TITLE
how to obtain bounding box files (.t7 or .pts)

### ISSUE THREAD

**Issue by iyildirim** [1adrianb/2D-and-3D-face-alignment#4]
Hi,

I am trying to run your demo, but I can't figure out your pipeline for obtaining the bounding box info files as required in utils.getFileLists(). I would appreciate any pointers on this.

In addition, what is the expected file format for the bounding box info?

Thanks
Ilker

**Comment by iyildirim** [comment]
Alright, figure this. Thanks.

**Comment by 1adrianb** [comment]
@iyildirim I am glad you sorted out.
Just in case someone else will have a similar question:
For simplicity, the code obtains the bounding box directly from the gt points. Therefore on new images one will have to run a face detector. However, technically, the code doesn't require a bounding box, but: a) a point located somewhere around the center of the face  and b) a rough estimate of the face scale.
