### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by xiendong** [1adrianb/2D-and-3D-face-alignment#41]
Hello, I noticed that some of the Lua dependecies require CUDA, so I'm wondering can this codebase run on MacOS? Thanks!

**Comment by 1adrianb** [comment]
@xiendong Sorry for delay. I am afraid that the provided models require cuda (i.e torch made a difference between cudnn and nn modules). While converting between the two is possible I am afraid that I don't have a torch7 setup on my machine any longer.
