### ISSUE TITLE
3D Alignment

### ISSUE THREAD

**Issue by ThomasNorr** [1adrianb/2D-and-3D-face-alignment#42]
Is the result reported for 3D face alignment in the paper the 2D error between the points and the prediction? If so, why is it not the error over all dimensions?

**Comment by 1adrianb** [comment]
Hi @Gnabe,

yes the results measure the error in 2D, between the projections of the 3D points. At the time the common practice was to measure it like this (i.e see how the results are reported for AFLW-PIFA or AFLW2000-3D). 

On 3DFAW for example, in a separate work, according to protocol we measured the error over all dimensions: https://arxiv.org/pdf/1609.09545.pdf
