### ISSUE TITLE
Query regarding dataset annotation

### ISSUE THREAD

**Issue by Rutvik21** [1adrianb/2D-and-3D-face-alignment#43]
Hey,
I want to make my own 3d face landmark annotation dataset to use it in my internship project. So how can I make one so that I can also use to train models for commercial purpose ?

Thanks.

**Comment by 1adrianb** [comment]
Hi @Rutvik21,

Our code and models are released under BSD3-Clause license. The data we trained on however is not owned by us and uses a different licensing (please see the respective authors webpages and licenses). I don't know if you can or not use them as such for commercial purposes.  Given this and the fact that I am not able nor qualified to offer any advice on this matter, I am afraid that you will need to seek a proper legal advice.
