### ISSUE TITLE
"Found 0 images" message

### ISSUE THREAD

**Issue by jgoenetxea** [1adrianb/2D-and-3D-face-alignment#6]
I have the application apparently working, but it looks like is not able to locate the images.
I have deducted the folder structure checking 'opts.lua' file.

My folder structure is:
2D-and-3D-face-alignment
2D-and-3D-face-alignment/dataset
2D-and-3D-face-alignment/dataset/LS3D-W/
2D-and-3D-face-alignment/dataset/LS3D-W/\*.t7  # All the LS3D-W dataset
2D-and-3D-face-alignment/dataset/LS3D-W/\*.jpg  # All the LS3D-W dataset
2D-and-3D-face-alignment/models
2D-and-3D-face-alignment/models/2D-FAN.t7  # A renamed version of 2D-FAN-generic.t7
2D-and-3D-face-alignment/LICENCE
2D-and-3D-face-alignment/main.lua
2D-and-3D-face-alignment/opts.lua
2D-and-3D-face-alignment/README.md
2D-and-3D-face-alignment/utils.lua

Is the folder structure wrong?

**Comment by 1adrianb** [comment]
The structure is corect, there was a problem in the input path in the code 'dataset/LS3D-W' vs 'dataset/LS3D-W/' (I should have used paths.concat to avoid) this. If you change it in the main, or provide it as an argument, ex: ```th main.lua -input dataset/LS3D-W/``` it should work.

**Comment by jgoenetxea** [comment]
Looks that it is working.

Thank you very much.
