### ISSUE TITLE
Dlib Face detection blocked

### ISSUE THREAD

**Issue by Yozey** [1adrianb/2D-and-3D-face-alignment#8]
Hello Adrian,

Thank you very much for sharing your code and model.
I have an error when running the landmark detection over an image without bounding box. It seems that the dlib detector doesn't work. 

The error could be found here: 

> /home/wisimage/torch/install/bin/luajit: ./facedetection_dlib.lua:21: Python error: opaque ref: call
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

I've mentioned that you have parsed the image into byte and HWC format.  I'am not quite sure how fb.python handle the python variable in Lua code but `print(py_img)`  looks fine.

Any ideas and suggestions are appreciated. Thank you

**Comment by 1adrianb** [comment]
Hi Yozey,
Are you sure your image is RGB and not RGBA instead?

**Comment by Yozey** [comment]
@1adrianb Yep i'm testing over ibug dataset with 2D FAN. They are just simple RGB images without depth information.

I added `print(py_img)` before `local dets = self.detector(py_img,py.int(1))` to check the image input, it looks like: 

>   [[[12 12 12]
>   [14 14 14]
>   [15 15 15]
>   ..., 
>   [55 55 55]
>   [57 57 57]
>   [51 51 51]]
> 
>  [[12 12 12]
>   [15 15 15]
>   [16 16 16]
>   ..., 
>   [54 54 54]
>   [49 49 49]
>   [52 52 52]]
> 
>  [[14 14 14]
>   [16 16 16]
>   [17 17 17]
>   ..., 
>   [60 60 60]
>   [55 55 55]
>   [55 55 55]]
> 
>  ..., 
>  [[23 23 23]
>   [21 21 21]
>   [22 22 22]
>   ..., 
>   [24 24 24]
>   [22 22 22]
>   [21 21 21]]
> 
>  [[26 26 26]
>   [25 25 25]
>   [29 29 29]
>   ..., 
>   [26 26 26]
>   [26 26 26]
>   [23 23 23]]
> 
>  [[24 24 24]
>   [21 21 21]
>   [24 24 24]
>   ..., 
>   [20 20 20]
>   [24 24 24]
>   [24 24 24]]]
which looks fine. 

`print(type(py_img))` gives 

> userdata
I'm not quite sure how to check the numpy variable type in Lua.

**Comment by 1adrianb** [comment]
Thanks a lot for the details provided. I will test it on the ibug dataset tomorrow and let you know where is the problem.
 Please do note however that dlib face detector doesn't work well with faces found in large poses and for more difficult cases a better, deeplearning based detector should be used.

**Comment by Yozey** [comment]
@1adrianb Thanks for your information.
I tested my dlib detector in python over ibug. It works by returning a rectangle object. I think dlib is all right. 

I limited the test image set(ibug) to only one image to ensure that Lua and python are processing the same image.

Same problem for the front-view photo from Internet. Thank you:)

**Comment by 1adrianb** [comment]
@Yozey I tested it on ibug images and it worked fine. I did fixed a few other minor things tho with this occasion. 

Could you please try to add:
`print(py_img.dtype, py_img.shape)`

You should get something like this(the image size will depend on the data):
uint8	 (800, 1200, 3)

Note that py_img is a reference to a python object (in this case a numpy array). This way you were unable to get the datatype of it using lua `type(...)`.

**Comment by Yozey** [comment]
@1adrianb Thank you for your information.

Even though the data type is all right, the problem remains unsolved.

> Scanning directory for data...	
> Found 135 images	
> 135 images require a face detector	
> Initialising python libs...	
> Initialising detector...	
> uint8
> (250, 985, 3)
> /home/wisimage/torch/install/bin/luajit: ./facedetection_dlib.lua:22: Python error: opaque ref: call
> RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

I doubt the problem probably comes from the dlib version etc.

**Comment by 1adrianb** [comment]
@Yozey That's weird since the data seems to be in the right format. They fb.python libray is however very sensitive to the libs version (it was not working for me with the latest numpy for example).
What I can try to do is to finally prepare a docker image which should allow reproducing the very same configuration.

**Comment by Yozey** [comment]
@1adrianb Thank you very much for your kind explanation.
Yep, I had un problem with the newest version of matplotlib. fb.python seems to be a little bit unpredictive.

**Comment by AaronJackson** [comment]
@1adrianb  I had this issue on quite a few images uploaded to my online demo. No idea why, but I managed to stop it happening (I think) by changing the image.load call to:
```
local img = image.load(fileList[i].image,3,'byte')
```
It's strange because I see you have some code to handle when a grey scale image is loaded, maybe it was the wrong type?

**Comment by 1adrianb** [comment]
Thanks @AaronJackson 
I am unsure however if this will fix this weird behavior since the image has the right size and data type in both scenarious. I runned it on the ibug images as Yozey did and I was unable to reproduce the error.
If you can send me a few samples where it failed I can have a look.

**Comment by 1adrianb** [comment]
@AaronJackson also, egarding the type, it is enforced to be byte before sending it to dlib (see the discussion above). 
If you enforce the byte type while loading the image you will have to convert it  back to float and rescale it from [0, 255] to [0,1] range.

**Comment by AaronJackson** [comment]
Good point! Ignore my suggestion everybody! haha

**Comment by 1adrianb** [comment]
@Yozey I have also released a python version of the code which should not exhibit this kind of weird error.

**Comment by Yozey** [comment]
@1adrianb Thank you very much. I'll take it a look.

**Comment by sumair95** [comment]
can we make haar cascade classifier compatible with dlib because hog detection rate is very low?
