### ISSUE TITLE
Magic 1.75 shift?

### ISSUE THREAD

**Issue by kartynnik** [1adrianb/2D-and-3D-face-alignment#9]
Could you please explain the intent behind the 1.75 shift in this line:

https://github.com/1adrianb/2D-and-3D-face-alignment/blob/7863dbf7979524512bfe77d31bab05e233b811d2/main.lua#L98

Thanks in advance!

**Comment by 1adrianb** [comment]
Hi Yury, 
It's a bad way of handling the 0 based vs 1 based annotations. This should be actually properly addressed in the transform function. I will fix this later tomorrow.
